# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer # Creates an AWS ELB/ALB for external access (most common for EKS)
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # The port the container listens on
